//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MainWindowButtonAdd {
            get {
                return ResourceManager.GetString("MainWindowButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Todo.
        /// </summary>
        public static string MainWindowHeader {
            get {
                return ResourceManager.GetString("MainWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string MainWindowHeaderTodos {
            get {
                return ResourceManager.GetString("MainWindowHeaderTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of todays active Todos: {0}.
        /// </summary>
        public static string MainWindowNumberOfTodaysTodos {
            get {
                return ResourceManager.GetString("MainWindowNumberOfTodaysTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show active.
        /// </summary>
        public static string MainWindowShowActive {
            get {
                return ResourceManager.GetString("MainWindowShowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string MainWindowShowAll {
            get {
                return ResourceManager.GetString("MainWindowShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show done.
        /// </summary>
        public static string MainWindowShowDone {
            get {
                return ResourceManager.GetString("MainWindowShowDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MainWindowVMNewDescription {
            get {
                return ResourceManager.GetString("MainWindowVMNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Todo.
        /// </summary>
        public static string MainWindowVMNewTodo {
            get {
                return ResourceManager.GetString("MainWindowVMNewTodo", resourceCulture);
            }
        }
    }
}
